_target_: dima.models.ScoreEstimator

config:
  add_cross_attention: false
  attention_head_size: 20
  attention_probs_dropout_prob: 0.1
  embedding_size: 1024
  hidden_dropout_prob: 0.1
  hidden_size: 320
  initializer_range: 0.02
  intermediate_size: 3072
  layer_norm_eps: 1e-12
  max_position_embeddings: 512
  norm_type: layernorm
  num_attention_heads: 16
  num_hidden_layers: 12
  qk_norm: false
  use_self_cond: true